region              = "us-west-2"
project_prefix      = "myproject"
s3_input_bucket     = "myproject-input-bucket"
s3_output_bucket    = "myproject-output-bucket"
lambda_function_name = "my-translation-lambda"
lambda_runtime       = "python3.12"
