function_name  = "translation_doc"
region          = "us-east-2"
project_prefix = "myproject"
input_bucket   = "myproject-input-bucket"
output_bucket  = "myproject-output-bucket"
lambda_runtime = "python3.9"
