function_name  = "translation_doc"
region         = "us-east-2"
project_prefix = "myproject"
bucket         = "myproject-input-bucket-law1223jj"
output_bucket  = "myproject-output-bucket-law189888kk"
lambda_runtime = "python3.11"
handler        = "translate_document.lambda_handler"
